export const products = [
  {
    id: 0,
    title: "shirt 1",
    imgURL: "shirt1.jpg",
    description: "shirt 1 description",
    type: "shirts",
  },
  {
    id: 1,
    title: "shirt 2",
    imgURL: "shirt2.jpg",
    description: "shirt 2 description",
    type: "shirts",
  },
  {
    id: 2,
    title: "shirt 3",
    imgURL: "shirt3.jpg",
    description: "shirt 3 description",
    type: "shirts",
  },
  {
    id: 3,
    title: "shirt 4",
    imgURL: "shirt4.jpg",
    description: "shirt 4 description",
    type: "shirts",
  },
  {
    id: 4,
    title: "shoes 1",
    imgURL: "shoes1.jpeg",
    description: "shoes 1 description",
    type: "shoes",
  },
  {
    id: 5,
    title: "shoes 2",
    imgURL: "shoes2.jpg",
    description: "shoes 2 description",
    type: "shoes",
  },
  {
    id: 6,
    title: "shoes 3",
    imgURL: "shoes3.jpg",
    description: "shoes 3 description",
    type: "shoes",
  },
  {
    id: 7,
    title: "shoes 4",
    imgURL: "shoes4.jpg",
    description: "shoes 4 description",
    type: "shoes",
  },
  {
    id: 8,
    title: "pants 1",
    imgURL: "pants1.jpg",
    description: "pants 1 description",
    type: "pants",
  },
  {
    id: 9,
    title: "pants 2",
    imgURL: "pants2.jpg",
    description: "pants 2 description",
    type: "pants",
  },
  {
    id: 10,
    title: "pants 3",
    imgURL: "pants3.jpg",
    description: "pants 3 description",
    type: "pants",
  },
  {
    id: 11,
    title: "pants 4",
    imgURL: "pants4.jpg",
    description: "pants 4 description",
    type: "pants",
  },
];
